apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jenf2635v-go
  janus-idp.io/tekton: jenf2635v-go
  backstage.io/kubernetes-id: jenf2635v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jenf2635v-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
